<?php
############################################################################
# IMGallery2: config.inc
# This file provides all general configuration data.
# Diese Datei enthδlt alle allgemeinen Konfigurations-Optionen.
############################################################################

// MySQL
$db_server = "";
$db_user = "";
$db_password = "";
$db_name = "";

// Sizes / Grφίen
$small = "400";
$medium = "600";
$big = "800";
$thumb = "100";

############################################################################
# End of File
############################################################################
?>